sudo: false
dist: trusty

language: python

before_install: |
  curl -O https://bin.equinox.io/c/jewmwFCp7w9/convox-stable-linux-amd64.tgz &&\
  tar zxvf convox-stable-linux-amd64.tgz -C /tmp

after_success:
  - convox deploy --app voyager --rack personal/convox-install-new-rack