services:
  web:
    build:
      path: .
      manifest: Dockerfile
    domain: ${DOMAIN}
    port: 80
    environment:
      - CONVOX_ENV=local_test
      - DB_HOST
      - DB_PORT
      - DB_DATABASE
      - DB_USERNAME
      - DB_PASSWORD
